#!/sbin/sh

PATH=/usr/sbin:/usr/bin:/usr/local/bin
COSIGND=/usr/local/projects/cosign/sbin/cosignd
export PATH 

case $1 in
    'start')
	if [ -x "$COSIGND" ]; then
	    su - cosign -c "$COSIGND"
	    echo 'Cosign daemon starting...'
	fi
    ;;

    'stop')
	#kill -15 `ps -def | grep [c]osignd | awk '{print $2}'`
    ;;

    'restart')
	#kill -HUP `ps -def | grep [c]osignd | awk '{print $2}'`
    ;;

    *)
	echo 'Usage: /etc/init.d/cosignd start'
    ;;
esac
exit 0
