#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: mkhashdirs 1|2"
    exit 1
fi

case "$1" in
1)
for i in a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 + -; do
    mkdir -- "$i"
done
;;

2)
for i in a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 + -; do
    for j in a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 + -; do
	mkdir -- "$i$j"
    done
done
;;

*)
    echo "Usage: mkhashdirs 1|2"
    exit 1
;;
esac
