#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: movehashdirs 1|2"
    exit 1
fi

case "$1" in
1)
ls | grep 'cosign.*=' | sed -e 's/^cosign.*=\(.\).*$/mv & \1/' | sh
;;

2)
ls | grep 'cosign.*=' | sed -e 's/^cosign.*=\(..\).*$/mv & \1/' | sh
;;

*)
    echo "Usage: movehashdirs 1|2"
    exit 1
;;
esac
