#!/bin/sh
# combine html parts into whole files

cd $1

for i in `/bin/ls *.html`; do
    if [ $i = "header.html" ]; then
	continue
    fi

    if [ $i = "footer.html" ]; then
	continue
    fi

    echo copying $i to $2/$i

    # this could also be m4, cpp, cc, whatever.
    # should probably be m4, actually.
    gcc -E -xc -P -C $i  >$2/$i
done

exit;

