#!/bin/sh
# combine html parts into whole files

cd $1

for i in `/bin/ls *.html`; do
    if [ $i = "header.html" ]; then
	continue
    fi

    if [ $i = "footer.html" ]; then
	continue
    fi

    echo copying $i to $2/$i

    if [ $i != "login.html" ]; then
	# strip the onload event where it doesn't make sense.

	/usr/bin/cat header.html $i footer.html \
		| /usr/bin/sed 's/onLoad="setfocus()"//' >$2/$i
    else
	/usr/bin/cat header.html login.html footer.html >$2/login.html
    fi
done

exit;

